# Generated by Django 2.2.7 on 2019-11-17 02:47

from django.db import migrations

def create_data(apps, schema_editor):
        Customers = apps.get_model('customers', 'Customers')
        Customers(
            first_name='Customers 001', 
            last_name='Customers last name 001', 
            email="customers001@email.com", 
            phone="00000000", 
            address="Customer 000 Address", 
            description= "Customer 001 description"
        ).save()

class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data)
    ]

   